baseURL: "https://inwardmovement.github.io/mettaconseilpro"
defaultContentLanguage: "fr"
languageCode: "fr"
title: "Metta Conseil"
canonifyURLs: true
disableLiveReload: true
metaDataFormat: yaml
rssLimit: 10
enableRobotsTXT: true
params:
  description: "Conseil en organisation et système d'information"
  author: "Victor Massé"
author:
  name: "Victor Massé"
taxonomies:
  category: categories
blackfriday:
  angledQuotes: true
  extensions:
    - hardLineBreak
    - noEmptyLineBeforeBlock
footnoteReturnLinkContents: "↑"
menu:
  mainleft:
    - Name: "Accueil"
      URL: "/"
      Identifier: "accueil"
      weight: 1
    - Name: "Clients"
      URL: "/clients/"
      Identifier: "clients"
      weight: 2
    - Name: "Tarifs"
      URL: "/tarifs/"
      Identifier: "tarifs"
      weight: 3
