baseURL: "https://pro.mettaconseil.fr"
defaultContentLanguage: "fr"
languageCode: "fr"
title: "Metta Conseil"
canonifyURLs: true
disableLiveReload: true
metaDataFormat: yaml
rssLimit: 10
enableRobotsTXT: true
params:
  description: "Conseil en organisation et système d'information"
  author: "Victor Massé"
author:
  name: "Victor Massé"
taxonomies:
  category: categories
blackfriday:
  angledQuotes: true
  extensions:
    - hardLineBreak
    - noEmptyLineBeforeBlock
footnoteReturnLinkContents: "↑"
menu:
  main:
    - Name: "Accueil"
      URL: "/"
      Identifier: "accueil"
      weight: 1
    - Name: "Prestations"
      URL: "/prestations/"
      Identifier: "prestations"
      weight: 2
    - Name: "Clients"
      URL: "/clients/"
      Identifier: "clients"
      weight: 3
    - Name: "Tarifs"
      URL: "/tarifs/"
      Identifier: "tarifs"
      weight: 4
    - Name: "À propos"
      URL: "/a-propos/"
      Identifier: "a-propos"
      weight: 5
  footer:
    - Name: "Mentions légales"
      URL: "/mentions-legales/"
      Identifier: "mentions-legales"
      weight: 1
