baseURL: "https://pro.mettaconseil.fr"
defaultContentLanguage: "fr"
languageCode: "fr"
title: "Metta Conseil"
canonifyURLs: true
disableLiveReload: true
metaDataFormat: yaml
rssLimit: 10
enableRobotsTXT: true
params:
  description: "Conseil en organisation et système d'information"
  author: "Victor Massé"
  header: "Conseil en organisation et SI"
  subheader: "pour les organisations progressistes"
author:
  name: "Victor Massé"
taxonomies:
  category: categories
blackfriday:
  angledQuotes: true
  extensions:
    - hardLineBreak
    - noEmptyLineBeforeBlock
footnoteReturnLinkContents: "↑"
menu:
  mainleft:
    - Name: "Prestations"
      URL: "/"
      Identifier: "prestations"
      weight: 1
    - Name: "Modules"
      URL: "/modules/"
      Identifier: "modules"
      weight: 2
    - Name: "Clients"
      URL: "/clients/"
      Identifier: "clients"
      weight: 3
    - Name: "Tarifs"
      URL: "/tarifs/"
      Identifier: "tarifs"
      weight: 4
    - Name: "À propos"
      URL: "/a-propos/"
      Identifier: "a-propos"
      weight: 5
